from time import strftime


class Structure:
    initial = 12

    time = strftime('%I:%M %p')
    date = strftime('%B %d, %Y')
    date_time = strftime('%m/%d/%Y - %I:%M %p')

    def __init__(self, wb):
        self.wb = wb

        self.unlocked = wb.add_format({'locked': False})

        self.white = wb.add_format({'border': 2})
        self.white.set_border_color('white')

        self.blue_component = wb.add_format({'border': 2})
        self.blue_component.set_bg_color('#1f497d')
        self.blue_component.set_border_color('white')
        self.blue_component.set_bold()
        self.blue_component.set_font_color('white')
        self.blue_component.set_align('vcenter')

        self.blue_left = wb.add_format({'border': 2})
        self.blue_left.set_bg_color('#1f497d')
        self.blue_left.set_text_wrap('True')
        self.blue_left.set_align('vcenter')
        self.blue_left.set_border_color('white')
        self.blue_left.set_bold()
        self.blue_left.set_left()
        self.blue_left.set_font_color('white')

        self.black_28 = wb.add_format({'border': 2})
        self.black_28.set_align('vcenter')
        self.black_28.set_border_color('white')
        self.black_28.set_bold()
        self.black_28.set_font_size(28)
        self.black_28.set_left()
        self.black_28.set_font_color('black')

        self.black_35 = wb.add_format({'border': 2})
        self.black_35.set_align('vcenter')
        self.black_35.set_border_color('white')
        self.black_35.set_bold()
        self.black_35.set_font_size(35)
        self.black_35.set_left()
        self.black_35.set_font_color('black')

        self.blank_12 = wb.add_format({'border': 2})
        self.blank_12.set_align('vcenter')
        self.blank_12.set_border_color('white')
        self.blank_12.set_bottom(1)
        self.blank_12.set_text_wrap('True')
        self.blank_12.set_font_size(12)
        self.blank_12.set_align('center')
        self.blank_12.set_font_color('black')

        self.blue_left_11 = wb.add_format({'border': 2})
        self.blue_left_11.set_bg_color('#1f497d')
        self.blue_left_11.set_text_wrap('True')
        self.blue_left_11.set_align('vcenter')
        self.blue_left_11.set_border_color('white')
        self.blue_left_11.set_bold()
        self.blue_left_11.set_font_size(11)
        self.blue_left_11.set_left()
        self.blue_left_11.set_font_color('white')

        self.alt_blue_left_11 = wb.add_format({'border': 2})
        self.alt_blue_left_11.set_bg_color('#4F81BD')
        self.alt_blue_left_11.set_text_wrap('True')
        self.alt_blue_left_11.set_align('vcenter')
        self.alt_blue_left_11.set_border_color('white')
        self.alt_blue_left_11.set_bold()
        self.alt_blue_left_11.set_font_size(11)
        self.alt_blue_left_11.set_left()
        self.alt_blue_left_11.set_font_color('white')

        self.blue_left_12 = wb.add_format({'border': 2})
        self.blue_left_12.set_bg_color('#1f497d')
        self.blue_left_12.set_font_size(12)
        self.blue_left_12.set_text_wrap('True')
        self.blue_left_12.set_text_wrap('True')
        self.blue_left_12.set_align('vcenter')
        self.blue_left_12.set_border_color('white')
        self.blue_left_12.set_bold()
        self.blue_left_12.set_left()
        self.blue_left_12.set_font_color('white')

        self.blue_left_16 = wb.add_format({'border': 2})
        self.blue_left_16.set_bg_color('#1f497d')
        self.blue_left_16.set_font_size(16)
        self.blue_left_16.set_text_wrap('True')
        self.blue_left_16.set_text_wrap('True')
        self.blue_left_16.set_align('vcenter')
        self.blue_left_16.set_border_color('white')
        self.blue_left_16.set_bold()
        self.blue_left_16.set_left()
        self.blue_left_16.set_font_color('white')

        self.blue_left_18 = wb.add_format({'border': 2})
        self.blue_left_18.set_bg_color('#1f497d')
        self.blue_left_18.set_font_size(18)
        self.blue_left_18.set_text_wrap('True')
        self.blue_left_18.set_text_wrap('True')
        self.blue_left_18.set_align('vcenter')
        self.blue_left_18.set_border_color('white')
        self.blue_left_18.set_bold()
        self.blue_left_18.set_left()
        self.blue_left_18.set_font_color('white')

        self.alt_blue_left_12 = wb.add_format({'border': 2})
        self.alt_blue_left_12.set_bg_color('#4F81BD')
        self.alt_blue_left_12.set_font_size(12)
        self.alt_blue_left_12.set_text_wrap('True')
        self.alt_blue_left_12.set_text_wrap('True')
        self.alt_blue_left_12.set_align('vcenter')
        self.alt_blue_left_12.set_border_color('white')
        self.alt_blue_left_12.set_bold()
        self.alt_blue_left_12.set_left()
        self.alt_blue_left_12.set_font_color('white')

        self.alt_blue_left_16 = wb.add_format({'border': 2})
        self.alt_blue_left_16.set_bg_color('#4F81BD')
        self.alt_blue_left_16.set_font_size(16)
        self.alt_blue_left_16.set_text_wrap('True')
        self.alt_blue_left_16.set_text_wrap('True')
        self.alt_blue_left_16.set_align('vcenter')
        self.alt_blue_left_16.set_border_color('white')
        self.alt_blue_left_16.set_bold()
        self.alt_blue_left_16.set_left()
        self.alt_blue_left_16.set_font_color('white')

        self.alt_blue_left_18 = wb.add_format({'border': 2})
        self.alt_blue_left_18.set_bg_color('#4F81BD')
        self.alt_blue_left_18.set_font_size(18)
        self.alt_blue_left_18.set_text_wrap('True')
        self.alt_blue_left_18.set_text_wrap('True')
        self.alt_blue_left_18.set_align('vcenter')
        self.alt_blue_left_18.set_border_color('white')
        self.alt_blue_left_18.set_bold()
        self.alt_blue_left_18.set_left()
        self.alt_blue_left_18.set_font_color('white')

        self.blue_left_14 = wb.add_format({'border': 2})
        self.blue_left_14.set_bg_color('#1f497d')
        self.blue_left_14.set_font_size(14)
        self.blue_left_14.set_text_wrap('True')
        self.blue_left_14.set_text_wrap('True')
        self.blue_left_14.set_align('vcenter')
        self.blue_left_14.set_border_color('white')
        self.blue_left_14.set_bold()
        self.blue_left_14.set_left()
        self.blue_left_14.set_font_color('white')

        self.alt_blue_left_14 = wb.add_format({'border': 2})
        self.alt_blue_left_14.set_bg_color('#4F81BD')
        self.alt_blue_left_14.set_font_size(14)
        self.alt_blue_left_14.set_text_wrap('True')
        self.alt_blue_left_14.set_text_wrap('True')
        self.alt_blue_left_14.set_align('vcenter')
        self.alt_blue_left_14.set_border_color('white')
        self.alt_blue_left_14.set_bold()
        self.alt_blue_left_14.set_left()
        self.alt_blue_left_14.set_font_color('white')

        self.blue_middle = wb.add_format({'border': 2})
        self.blue_middle.set_bg_color('#1f497d')
        self.blue_middle.set_align('center')
        self.blue_middle.set_text_wrap('True')
        self.blue_middle.set_align('vcenter')
        self.blue_middle.set_border_color('white')
        self.blue_middle.set_bold()
        self.blue_middle.set_font_color('white')

        self.blue_middle_12 = wb.add_format({'border': 2})
        self.blue_middle_12.set_bg_color('#1f497d')
        self.blue_middle_12.set_font_size(12)
        self.blue_middle_12.set_text_wrap('True')
        self.blue_middle_12.set_text_wrap('True')
        self.blue_middle_12.set_align('vcenter')
        self.blue_middle_12.set_align('center')
        self.blue_middle_12.set_border_color('white')
        self.blue_middle_12.set_bold()
        self.blue_middle_12.set_font_color('white')

        self.blue_middle_16 = wb.add_format({'border': 2})
        self.blue_middle_16.set_bg_color('#1f497d')
        self.blue_middle_16.set_font_size(16)
        self.blue_middle_16.set_text_wrap('True')
        self.blue_middle_16.set_text_wrap('True')
        self.blue_middle_16.set_align('vcenter')
        self.blue_middle_16.set_align('center')
        self.blue_middle_16.set_border_color('white')
        self.blue_middle_16.set_bold()
        self.blue_middle_16.set_font_color('white')

        self.blue_middle_14 = wb.add_format({'border': 2})
        self.blue_middle_14.set_bg_color('#1f497d')
        self.blue_middle_14.set_font_size(14)
        self.blue_middle_14.set_text_wrap('True')
        self.blue_middle_14.set_text_wrap('True')
        self.blue_middle_14.set_align('vcenter')
        self.blue_middle_14.set_align('center')
        self.blue_middle_14.set_border_color('white')
        self.blue_middle_14.set_bold()
        self.blue_middle_14.set_font_color('white')

        self.purple_middle = wb.add_format({'border': 2})
        self.purple_middle.set_bg_color('#7030A0')
        self.purple_middle.set_align('center')
        self.purple_middle.set_text_wrap('True')
        self.purple_middle.set_align('vcenter')
        self.purple_middle.set_border_color('white')
        self.purple_middle.set_bold()
        self.purple_middle.set_font_color('white')

        self.purple_middle_12 = wb.add_format({'border': 2})
        self.purple_middle_12.set_bg_color('#7030A0')
        self.purple_middle_12.set_align('center')
        self.purple_middle_12.set_text_wrap('True')
        self.purple_middle_12.set_align('vcenter')
        self.purple_middle_12.set_border_color('white')
        self.purple_middle_12.set_bold()
        self.purple_middle_12.set_font_size(12)
        self.purple_middle_12.set_font_color('white')

        self.aqua_middle = wb.add_format({'border': 2})
        self.aqua_middle.set_bg_color('#31869B')
        self.aqua_middle.set_align('center')
        self.aqua_middle.set_text_wrap('True')
        self.aqua_middle.set_align('vcenter')
        self.aqua_middle.set_border_color('white')
        self.aqua_middle.set_bold()
        self.aqua_middle.set_font_color('white')

        self.aqua_middle_12 = wb.add_format({'border': 2})
        self.aqua_middle_12.set_bg_color('#31869B')
        self.aqua_middle_12.set_align('center')
        self.aqua_middle_12.set_text_wrap('True')
        self.aqua_middle_12.set_align('vcenter')
        self.aqua_middle_12.set_border_color('white')
        self.aqua_middle_12.set_bold()
        self.aqua_middle_12.set_font_size(12)
        self.aqua_middle_12.set_font_color('white')

        self.aqua_middle_14 = wb.add_format({'border': 2})
        self.aqua_middle_14.set_bg_color('#31869B')
        self.aqua_middle_14.set_align('center')
        self.aqua_middle_14.set_text_wrap('True')
        self.aqua_middle_14.set_align('vcenter')
        self.aqua_middle_14.set_border_color('white')
        self.aqua_middle_14.set_bold()
        self.aqua_middle_14.set_font_size(12)
        self.aqua_middle_14.set_font_color('white')

        self.aqua_left_12 = wb.add_format({'border': 2})
        self.aqua_left_12.set_bg_color('#31869B')
        self.aqua_left_12.set_text_wrap('True')
        self.aqua_left_12.set_align('vcenter')
        self.aqua_left_12.set_border_color('white')
        self.aqua_left_12.set_bold()
        self.aqua_left_12.set_left()
        self.aqua_left_12.set_font_size(12)
        self.aqua_left_12.set_font_color('white')

        self.aqua_left_11 = wb.add_format({'border': 2})
        self.aqua_left_11.set_bg_color('#31869B')
        self.aqua_left_11.set_text_wrap('True')
        self.aqua_left_11.set_align('vcenter')
        self.aqua_left_11.set_border_color('white')
        self.aqua_left_11.set_bold()
        self.aqua_left_11.set_left()
        self.aqua_left_11.set_font_size(11)
        self.aqua_left_11.set_font_color('white')

        self.blue_middle_huge = wb.add_format({'border': 2})
        self.blue_middle_huge.set_bg_color('#1f497d')
        self.blue_middle_huge.set_align('center')
        self.blue_middle_huge.set_text_wrap('True')
        self.blue_middle_huge.set_align('vcenter')
        self.blue_middle_huge.set_border_color('white')
        self.blue_middle_huge.set_bold()
        self.blue_middle_huge.set_font_color('white')
        self.blue_middle_huge.set_font_size('26')

        self.blue_middle_26 = wb.add_format({'border': 2})
        self.blue_middle_26.set_bg_color('#1f497d')
        self.blue_middle_26.set_align('center')
        self.blue_middle_26.set_text_wrap('True')
        self.blue_middle_26.set_align('vcenter')
        self.blue_middle_26.set_border_color('white')
        self.blue_middle_26.set_bold()
        self.blue_middle_26.set_font_color('white')
        self.blue_middle_26.set_font_size('26')

        self.blue_middle_huge_left = wb.add_format({'border': 2})
        self.blue_middle_huge_left.set_bg_color('#1f497d')
        self.blue_middle_huge_left.set_text_wrap('True')
        self.blue_middle_huge_left.set_align('vcenter')
        self.blue_middle_huge_left.set_border_color('white')
        self.blue_middle_huge_left.set_bold()
        self.blue_middle_huge_left.set_font_color('white')
        self.blue_middle_huge_left.set_font_size('24')
        self.blue_middle_huge_left.set_left()

        self.blue_middle_22 = wb.add_format({'border': 2})
        self.blue_middle_22.set_bg_color('#1f497d')
        self.blue_middle_22.set_text_wrap('True')
        self.blue_middle_22.set_align('vcenter')
        self.blue_middle_22.set_border_color('white')
        self.blue_middle_22.set_bold()
        self.blue_middle_22.set_font_color('white')
        self.blue_middle_22.set_font_size('22')
        self.blue_middle_22.set_left()

        self.alt_blue_middle_22 = wb.add_format({'border': 2})
        self.alt_blue_middle_22.set_bg_color('#4F81BD')
        self.alt_blue_middle_22.set_text_wrap('True')
        self.alt_blue_middle_22.set_align('vcenter')
        self.alt_blue_middle_22.set_border_color('white')
        self.alt_blue_middle_22.set_bold()
        self.alt_blue_middle_22.set_font_color('white')
        self.alt_blue_middle_22.set_font_size('22')
        self.alt_blue_middle_22.set_left()

        self.blue_middle_gigantic = wb.add_format({'border': 2})
        self.blue_middle_gigantic.set_bg_color('#1f497d')
        self.blue_middle_gigantic.set_align('center')
        self.blue_middle_gigantic.set_text_wrap('True')
        self.blue_middle_gigantic.set_align('vcenter')
        self.blue_middle_gigantic.set_border_color('white')
        self.blue_middle_gigantic.set_bold()
        self.blue_middle_gigantic.set_font_color('white')
        self.blue_middle_gigantic.set_font_size('24')

        self.blue_middle_24 = wb.add_format({'border': 2})
        self.blue_middle_24.set_bg_color('#1f497d')
        self.blue_middle_24.set_align('center')
        self.blue_middle_24.set_text_wrap('True')
        self.blue_middle_24.set_align('vcenter')
        self.blue_middle_24.set_border_color('white')
        self.blue_middle_24.set_bold()
        self.blue_middle_24.set_font_color('white')
        self.blue_middle_24.set_font_size('24')

        self.blue_middle_big = wb.add_format({'border': 2})
        self.blue_middle_big.set_bg_color('#1f497d')
        self.blue_middle_big.set_align('center')
        self.blue_middle_big.set_align('vcenter')
        self.blue_middle_big.set_border_color('white')
        self.blue_middle_big.set_bold()
        self.blue_middle_big.set_font_color('white')
        self.blue_middle_big.set_font_size('12')

        self.blue_middle_bigger = wb.add_format({'border': 2})
        self.blue_middle_bigger.set_bg_color('#1f497d')
        self.blue_middle_bigger.set_align('center')
        self.blue_middle_bigger.set_align('vcenter')
        self.blue_middle_bigger.set_border_color('white')
        self.blue_middle_bigger.set_bold()
        self.blue_middle_bigger.set_font_color('white')
        self.blue_middle_bigger.set_font_size('14')

        self.alt_blue_middle_bigger = wb.add_format({'border': 2})
        self.alt_blue_middle_bigger.set_bg_color('#1f497d')
        self.alt_blue_middle_bigger.set_align('center')
        self.alt_blue_middle_bigger.set_align('vcenter')
        self.alt_blue_middle_bigger.set_border_color('white')
        self.alt_blue_middle_bigger.set_bold()
        self.alt_blue_middle_bigger.set_font_color('white')
        self.alt_blue_middle_bigger.set_font_size('14')

        self.alt_blue_middle_16 = wb.add_format({'border': 2})
        self.alt_blue_middle_16.set_bg_color('#4F81BD')
        self.alt_blue_middle_16.set_align('center')
        self.alt_blue_middle_16.set_align('vcenter')
        self.alt_blue_middle_16.set_border_color('white')
        self.alt_blue_middle_16.set_bold()
        self.alt_blue_middle_16.set_font_color('white')
        self.alt_blue_middle_16.set_font_size(16)

        self.alt_blue_middle_12 = wb.add_format({'border': 2})
        self.alt_blue_middle_12.set_bg_color('#4F81BD')
        self.alt_blue_middle_12.set_align('center')
        self.alt_blue_middle_12.set_align('vcenter')
        self.alt_blue_middle_12.set_border_color('white')
        self.alt_blue_middle_12.set_bold()
        self.alt_blue_middle_12.set_font_color('white')
        self.alt_blue_middle_12.set_font_size(12)

        self.alt_blue_middle_14 = wb.add_format({'border': 2})
        self.alt_blue_middle_14.set_bg_color('#4F81BD')
        self.alt_blue_middle_14.set_align('center')
        self.alt_blue_middle_14.set_align('vcenter')
        self.alt_blue_middle_14.set_border_color('white')
        self.alt_blue_middle_14.set_bold()
        self.alt_blue_middle_14.set_font_color('white')
        self.alt_blue_middle_14.set_font_size(14)

        self.alt_blue_middle = wb.add_format({'border': 2})
        self.alt_blue_middle.set_bg_color('#4F81BD')
        self.alt_blue_middle.set_align('center')
        self.alt_blue_middle.set_text_wrap('True')
        self.alt_blue_middle.set_align('vcenter')
        self.alt_blue_middle.set_border_color('white')
        self.alt_blue_middle.set_bold()
        self.alt_blue_middle.set_font_color('white')

        self.alt_blue_middle_huge = wb.add_format({'border': 2})
        self.alt_blue_middle_huge.set_bg_color('#4F81BD')
        self.alt_blue_middle_huge.set_align('center')
        self.alt_blue_middle_huge.set_text_wrap('True')
        self.alt_blue_middle_huge.set_align('vcenter')
        self.alt_blue_middle_huge.set_border_color('white')
        self.alt_blue_middle_huge.set_bold()
        self.alt_blue_middle_huge.set_font_color('white')
        self.alt_blue_middle_huge.set_font_size('26')

        self.alt_blue_middle_huge_left = wb.add_format({'border': 2})
        self.alt_blue_middle_huge_left.set_bg_color('#4F81BD')
        self.alt_blue_middle_huge_left.set_text_wrap('True')
        self.alt_blue_middle_huge_left.set_align('vcenter')
        self.alt_blue_middle_huge_left.set_border_color('white')
        self.alt_blue_middle_huge_left.set_bold()
        self.alt_blue_middle_huge_left.set_font_color('white')
        self.alt_blue_middle_huge_left.set_font_size('26')
        self.alt_blue_middle_huge_left.set_left()

        self.alt_blue_left = wb.add_format({'border': 2})
        self.alt_blue_left.set_bg_color('#4F81BD')
        self.alt_blue_left.set_text_wrap('True')
        self.alt_blue_left.set_align('vcenter')
        self.alt_blue_left.set_border_color('white')
        self.alt_blue_left.set_bold()
        self.alt_blue_left.set_left()
        self.alt_blue_left.set_font_color('white')

        self.alt_blue_rich_normal = wb.add_format({'border': 2})
        self.alt_blue_rich_normal.set_bg_color('#4F81BD')
        self.alt_blue_rich_normal.set_align('center')
        self.alt_blue_rich_normal.set_text_wrap('True')
        self.alt_blue_rich_normal.set_align('vcenter')
        self.alt_blue_rich_normal.set_border_color('white')
        self.alt_blue_rich_normal.set_font_size('11')
        self.alt_blue_rich_normal.set_font_color('white')

        self.alt_blue_rich_bold = wb.add_format({'border': 2})
        self.alt_blue_rich_bold.set_bg_color('#4F81BD')
        self.alt_blue_rich_bold.set_align('center')
        self.alt_blue_rich_bold.set_text_wrap('True')
        self.alt_blue_rich_bold.set_align('vcenter')
        self.alt_blue_rich_bold.set_border_color('white')
        self.alt_blue_rich_bold.set_font_size('12')
        self.alt_blue_rich_bold.set_bold()
        self.alt_blue_rich_bold.set_font_color('white')

        self.bold_text = wb.add_format()
        self.bold_text.set_font_size('12')
        self.bold_text.set_bold()

        self.teal_left = wb.add_format({'border': 2})
        self.teal_left.set_bg_color('#00B0F0')
        self.teal_left.set_align('left')
        self.teal_left.set_align('vcenter')
        self.teal_left.set_border_color('white')
        self.teal_left.set_bold()
        self.teal_left.set_font_color('white')
        self.teal_left.set_font_size('18')

        self.teal_middle = wb.add_format({'border': 2})
        self.teal_middle.set_bg_color('#00B0F0')
        self.teal_middle.set_align('center')
        self.teal_middle.set_align('vcenter')
        self.teal_middle.set_border_color('white')
        self.teal_middle.set_bold()
        self.teal_middle.set_font_color('white')
        self.teal_middle.set_font_size('18')
        self.teal_middle.set_align('vcenter')

        self.teal_middle_16 = wb.add_format({'border': 2})
        self.teal_middle_16.set_bg_color('#00B0F0')
        self.teal_middle_16.set_align('center')
        self.teal_middle_16.set_align('vcenter')
        self.teal_middle_16.set_border_color('white')
        self.teal_middle_16.set_bold()
        self.teal_middle_16.set_font_color('white')
        self.teal_middle_16.set_font_size('16')
        self.teal_middle_16.set_align('vcenter')

        self.teal_middle_14 = wb.add_format({'border': 2})
        self.teal_middle_14.set_bg_color('#00B0F0')
        self.teal_middle_14.set_align('center')
        self.teal_middle_14.set_align('vcenter')
        self.teal_middle_14.set_border_color('white')
        self.teal_middle_14.set_bold()
        self.teal_middle_14.set_font_color('white')
        self.teal_middle_14.set_font_size('14')
        self.teal_middle_14.set_align('vcenter')

        self.teal_middle_12 = wb.add_format({'border': 2})
        self.teal_middle_12.set_bg_color('#00B0F0')
        self.teal_middle_12.set_align('center')
        self.teal_middle_12.set_align('vcenter')
        self.teal_middle_12.set_border_color('white')
        self.teal_middle_12.set_bold()
        self.teal_middle_12.set_font_color('white')
        self.teal_middle_12.set_font_size('12')
        self.teal_middle_12.set_align('vcenter')

        self.teal_left_14 = wb.add_format({'border': 2})
        self.teal_left_14.set_bg_color('#00B0F0')
        self.teal_left_14.set_align('left')
        self.teal_left_14.set_align('vcenter')
        self.teal_left_14.set_border_color('white')
        self.teal_left_14.set_bold()
        self.teal_left_14.set_font_color('white')
        self.teal_left_14.set_font_size('14')
        self.teal_left_14.set_align('vcenter')

        self.pale_teal_middle_12 = wb.add_format({'border': 2})
        self.pale_teal_middle_12.set_bg_color('#B7DEE8')
        self.pale_teal_middle_12.set_align('center')
        self.pale_teal_middle_12.set_align('vcenter')
        self.pale_teal_middle_12.set_border_color('white')
        self.pale_teal_middle_12.set_bold()
        self.pale_teal_middle_12.set_font_color('black')
        self.pale_teal_middle_12.set_font_size('12')
        self.pale_teal_middle_12.set_align('vcenter')

        self.pale_teal_middle_12_normal = wb.add_format({'border': 2})
        self.pale_teal_middle_12_normal.set_bg_color('#B7DEE8')
        self.pale_teal_middle_12_normal.set_align('center')
        self.pale_teal_middle_12_normal.set_align('vcenter')
        self.pale_teal_middle_12_normal.set_border_color('white')
        self.pale_teal_middle_12_normal.set_font_color('black')
        self.pale_teal_middle_12_normal.set_font_size('12')
        self.pale_teal_middle_12_normal.set_align('vcenter')

        self.pale_teal_middle_11_normal = wb.add_format({'border': 2})
        self.pale_teal_middle_11_normal.set_bg_color('#B7DEE8')
        self.pale_teal_middle_11_normal.set_align('center')
        self.pale_teal_middle_11_normal.set_align('vcenter')
        self.pale_teal_middle_11_normal.set_border_color('white')
        self.pale_teal_middle_11_normal.set_font_color('black')
        self.pale_teal_middle_11_normal.set_font_size('11')
        self.pale_teal_middle_11_normal.set_align('vcenter')

        self.teal_middle_merge = wb.add_format({'border': 2})
        self.teal_middle_merge.set_bg_color('#00B0F0')
        self.teal_middle_merge.set_align('center')
        self.teal_middle_merge.set_border_color('white')
        self.teal_middle_merge.set_bold()
        self.teal_middle_merge.set_font_color('white')
        self.teal_middle_merge.set_font_size('18')
        self.teal_middle_merge.set_align('vcenter')

        self.grey_middle_11 = wb.add_format({'border': 2})
        self.grey_middle_11.set_bg_color('#808080')
        self.grey_middle_11.set_align('center')
        self.grey_middle_11.set_border_color('white')
        self.grey_middle_11.set_bold()
        self.grey_middle_11.set_font_color('white')
        self.grey_middle_11.set_font_size('11')
        self.grey_middle_11.set_align('vcenter')

        self.grey_area = wb.add_format()
        self.grey_area.set_bg_color('gray')

        self.light_grey_background = wb.add_format({'border': 2})
        self.light_grey_background.set_bg_color('#BFBFBF')
        self.light_grey_background.set_border_color('white')

        self.dark_grey_background = wb.add_format({'border': 2})
        self.dark_grey_background.set_bg_color('#808080')
        self.dark_grey_background.set_border_color('white')

        self.dark_grey_middle = wb.add_format({'border': 2})
        self.dark_grey_middle.set_bg_color('#595959')
        self.dark_grey_middle.set_align('center')
        self.dark_grey_middle.set_align('vcenter')
        self.dark_grey_middle.set_border_color('white')
        self.dark_grey_middle.set_bold()
        self.dark_grey_middle.set_font_color('white')
        self.dark_grey_middle.set_align('vcenter')

        self.dark_grey_middle_bigger = wb.add_format({'border': 2})
        self.dark_grey_middle_bigger.set_bg_color('#595959')
        self.dark_grey_middle_bigger.set_align('center')
        self.dark_grey_middle_bigger.set_align('vcenter')
        self.dark_grey_middle_bigger.set_border_color('white')
        self.dark_grey_middle_bigger.set_bold()
        self.dark_grey_middle_bigger.set_font_color('white')
        self.dark_grey_middle_bigger.set_align('vcenter')
        self.dark_grey_middle_bigger.set_font_size(12)

        self.dark_grey_left_12 = wb.add_format({'border': 2})
        self.dark_grey_left_12.set_bg_color('#595959')
        self.dark_grey_left_12.set_align('vcenter')
        self.dark_grey_left_12.set_border_color('white')
        self.dark_grey_left_12.set_bold()
        self.dark_grey_left_12.set_left()
        self.dark_grey_left_12.set_font_color('white')
        self.dark_grey_left_12.set_align('vcenter')
        self.dark_grey_left_12.set_font_size(12)

        self.dark_grey_middle_14 = wb.add_format({'border': 2})
        self.dark_grey_middle_14.set_bg_color('#808080')
        self.dark_grey_middle_14.set_align('vcenter')
        self.dark_grey_middle_14.set_border_color('white')
        self.dark_grey_middle_14.set_bold()
        self.dark_grey_middle_14.set_font_color('white')
        self.dark_grey_middle_14.set_align('center')
        self.dark_grey_middle_14.set_font_size(14)

        self.light_grey_middle_12 = wb.add_format({'border': 2})
        self.light_grey_middle_12.set_bg_color('#A6A6A6')
        self.light_grey_middle_12.set_align('vcenter')
        self.light_grey_middle_12.set_border_color('white')
        self.light_grey_middle_12.set_font_color('black')
        self.light_grey_middle_12.set_align('center')
        self.light_grey_middle_12.set_font_size(12)

        self.light_grey_middle_12_bold = wb.add_format({'border': 2})
        self.light_grey_middle_12_bold.set_bg_color('#A6A6A6')
        self.light_grey_middle_12_bold.set_align('vcenter')
        self.light_grey_middle_12_bold.set_border_color('white')
        self.light_grey_middle_12_bold.set_font_color('white')
        self.light_grey_middle_12_bold.set_bold()
        self.light_grey_middle_12_bold.set_align('center')
        self.light_grey_middle_12_bold.set_font_size(12)

        self.light_grey_middle_14 = wb.add_format({'border': 2})
        self.light_grey_middle_14.set_bg_color('#A6A6A6')
        self.light_grey_middle_14.set_align('vcenter')
        self.light_grey_middle_14.set_border_color('white')
        self.light_grey_middle_14.set_font_color('black')
        self.light_grey_middle_14.set_align('center')
        self.light_grey_middle_14.set_font_size(14)

        self.light_grey_middle_16 = wb.add_format({'border': 2})
        self.light_grey_middle_16.set_bg_color('#A6A6A6')
        self.light_grey_middle_16.set_align('vcenter')
        self.light_grey_middle_16.set_border_color('white')
        self.light_grey_middle_16.set_font_color('black')
        self.light_grey_middle_16.set_align('center')
        self.light_grey_middle_16.set_font_size(16)

        self.dark_grey_left_11 = wb.add_format({'border': 2})
        self.dark_grey_left_11.set_bg_color('#595959')
        self.dark_grey_left_11.set_align('vcenter')
        self.dark_grey_left_11.set_border_color('white')
        self.dark_grey_left_11.set_bold()
        self.dark_grey_left_11.set_left()
        self.dark_grey_left_11.set_font_color('white')
        self.dark_grey_left_11.set_align('vcenter')
        self.dark_grey_left_11.set_font_size(11)

        self.dark_grey_middle_12 = wb.add_format({'border': 2})
        self.dark_grey_middle_12.set_bg_color('#595959')
        self.dark_grey_middle_12.set_align('vcenter')
        self.dark_grey_middle_12.set_border_color('white')
        self.dark_grey_middle_12.set_bold()
        self.dark_grey_middle_12.set_align('center')
        self.dark_grey_middle_12.set_font_color('white')
        self.dark_grey_middle_12.set_font_size(12)

        self.dark_grey_middle_16 = wb.add_format({'border': 2})
        self.dark_grey_middle_16.set_bg_color('#595959')
        self.dark_grey_middle_16.set_align('vcenter')
        self.dark_grey_middle_16.set_border_color('white')
        self.dark_grey_middle_16.set_bold()
        self.dark_grey_middle_16.set_align('center')
        self.dark_grey_middle_16.set_font_color('white')
        self.dark_grey_middle_16.set_font_size(16)

        self.dark_grey_left = wb.add_format({'border': 2})
        self.dark_grey_left.set_bg_color('#595959')
        self.dark_grey_left.set_border_color('white')
        self.dark_grey_left.set_bold()
        self.dark_grey_left.set_font_color('white')
        self.dark_grey_left.set_align('vcenter')
        self.dark_grey_left.set_left()

        self.light_grey_middle = wb.add_format({'border': 2})
        self.light_grey_middle.set_bg_color('#A6A6A6')
        self.light_grey_middle.set_align('center')
        self.light_grey_middle.set_align('vcenter')
        self.light_grey_middle.set_border_color('white')
        self.light_grey_middle.set_bold()
        self.light_grey_middle.set_font_color('white')
        self.light_grey_middle.set_align('vcenter')

        self.bold = wb.add_format({'bold': True})
        self.bold.set_font_size('13')

        self.bold_middle = wb.add_format()
        self.bold_middle.set_bold()
        self.bold_middle.set_align('center')
        self.bold_middle.set_font('13')

        self.blue_font = wb.add_format({'border': 2})
        self.blue_font.set_bold()
        self.blue_font.set_font_size('14')
        self.blue_font.set_font_color('#1f497d')
        self.blue_font.set_border_color('white')

        self.blue_font_22 = wb.add_format({'border': 2})
        self.blue_font_22.set_bold()
        self.blue_font_22.set_font_size('22')
        self.blue_font_22.set_font_color('#1f497d')
        self.blue_font_22.set_border_color('white')

        self.big_blue_font = wb.add_format({'border': 2})
        self.big_blue_font.set_bold()
        self.big_blue_font.set_font_size('16')
        self.big_blue_font.set_font_color('#1f497d')
        self.big_blue_font.set_border_color('white')

        self.italic_blue_font = wb.add_format({'border': 2})
        self.italic_blue_font.set_italic()
        self.italic_blue_font.set_font_size('12')
        self.italic_blue_font.set_font_color('#1f497d')
        self.italic_blue_font.set_border_color('white')

        self.bold_italic_blue_font = wb.add_format({'border': 2})
        self.bold_italic_blue_font.set_italic()
        self.bold_italic_blue_font.set_bold()
        self.bold_italic_blue_font.set_font_size('14')
        self.bold_italic_blue_font.set_font_color('#1f497d')
        self.bold_italic_blue_font.set_border_color('white')
        self.middle = wb.add_format()
        self.middle.set_align('center')

        self.bold_italic_green_font = wb.add_format({'border': 2})
        self.bold_italic_green_font.set_italic()
        self.bold_italic_green_font.set_bold()
        self.bold_italic_green_font.set_font_size('14')
        self.bold_italic_green_font.set_font_color('#00B050')
        self.bold_italic_green_font.set_border_color('white')

        self.good_cell = wb.add_format({'border': 2})
        self.good_cell.set_align('center')
        self.good_cell.set_align('vcenter')
        self.good_cell.set_bold()
        self.good_cell.set_text_wrap('True')
        self.good_cell.set_bg_color('#00B050')
        self.good_cell.set_font_color('white')
        self.good_cell.set_border_color('white')

        self.left_green = wb.add_format({'border': 2})
        self.left_green.set_align('vcenter')
        self.left_green.set_bold()
        self.left_green.set_text_wrap('True')
        self.left_green.set_bg_color('#00B050')
        self.left_green.set_font_color('white')
        self.left_green.set_border_color('white')

        self.middle_green_11 = wb.add_format({'border': 2})
        self.middle_green_11.set_align('center')
        self.middle_green_11.set_align('vcenter')
        self.middle_green_11.set_bold()
        self.middle_green_11.set_font_size(11)
        self.middle_green_11.set_text_wrap('True')
        self.middle_green_11.set_bg_color('#76933C')
        self.middle_green_11.set_font_color('white')
        self.middle_green_11.set_border_color('white')

        self.middle_green_16 = wb.add_format({'border': 2})
        self.middle_green_16.set_align('center')
        self.middle_green_16.set_align('vcenter')
        self.middle_green_16.set_bold()
        self.middle_green_16.set_font_size(16)
        self.middle_green_16.set_text_wrap('True')
        self.middle_green_16.set_bg_color('#76933C')
        self.middle_green_16.set_font_color('white')
        self.middle_green_16.set_border_color('white')

        self.middle_green_14 = wb.add_format({'border': 2})
        self.middle_green_14.set_align('center')
        self.middle_green_14.set_align('vcenter')
        self.middle_green_14.set_bold()
        self.middle_green_14.set_font_size(14)
        self.middle_green_14.set_text_wrap('True')
        self.middle_green_14.set_bg_color('#76933C')
        self.middle_green_14.set_font_color('white')
        self.middle_green_14.set_border_color('white')

        self.middle_green_12 = wb.add_format({'border': 2})
        self.middle_green_12.set_align('center')
        self.middle_green_12.set_align('vcenter')
        self.middle_green_12.set_bold()
        self.middle_green_12.set_font_size(12)
        self.middle_green_12.set_text_wrap('True')
        self.middle_green_12.set_bg_color('#76933C')
        self.middle_green_12.set_font_color('white')
        self.middle_green_12.set_border_color('white')

        self.bad_cell = wb.add_format({'border': 2})
        self.bad_cell.set_align('center')
        self.bad_cell.set_align('vcenter')
        self.bad_cell.set_bold()
        self.bad_cell.set_text_wrap('True')
        self.bad_cell.set_bg_color('#FF0000')
        self.bad_cell.set_font_color('white')
        self.bad_cell.set_border_color('white')

        self.red_middle_18 = wb.add_format({'border': 2})
        self.red_middle_18.set_align('center')
        self.red_middle_18.set_align('vcenter')
        self.red_middle_18.set_bold()
        self.red_middle_18.set_font_size(18)
        self.red_middle_18.set_text_wrap('True')
        self.red_middle_18.set_bg_color('#FF0000')
        self.red_middle_18.set_font_color('white')
        self.red_middle_18.set_border_color('white')

        self.light_red_middle_14 = wb.add_format({'border': 2})
        self.light_red_middle_14.set_align('center')
        self.light_red_middle_14.set_align('vcenter')
        self.light_red_middle_14.set_bold()
        self.light_red_middle_14.set_font_size(14)
        self.light_red_middle_14.set_text_wrap('True')
        self.light_red_middle_14.set_bg_color('#C0504D')
        self.light_red_middle_14.set_font_color('white')
        self.light_red_middle_14.set_border_color('white')

        self.light_red_middle_11 = wb.add_format({'border': 2})
        self.light_red_middle_11.set_align('center')
        self.light_red_middle_11.set_align('vcenter')
        self.light_red_middle_11.set_bold()
        self.light_red_middle_11.set_font_size(11)
        self.light_red_middle_11.set_text_wrap('True')
        self.light_red_middle_11.set_bg_color('#C0504D')
        self.light_red_middle_11.set_font_color('white')
        self.light_red_middle_11.set_border_color('white')

        self.light_red_middle_12 = wb.add_format({'border': 2})
        self.light_red_middle_12.set_align('center')
        self.light_red_middle_12.set_align('vcenter')
        self.light_red_middle_12.set_bold()
        self.light_red_middle_12.set_font_size(12)
        self.light_red_middle_12.set_text_wrap('True')
        self.light_red_middle_12.set_bg_color('#C0504D')
        self.light_red_middle_12.set_font_color('white')
        self.light_red_middle_12.set_border_color('white')

        self.light_red_middle_16 = wb.add_format({'border': 2})
        self.light_red_middle_16.set_align('center')
        self.light_red_middle_16.set_align('vcenter')
        self.light_red_middle_16.set_bold()
        self.light_red_middle_16.set_font_size(16)
        self.light_red_middle_16.set_text_wrap('True')
        self.light_red_middle_16.set_bg_color('#C0504D')
        self.light_red_middle_16.set_font_color('white')
        self.light_red_middle_16.set_border_color('white')

        self.pale_red_middle_12 = wb.add_format({'border': 2})
        self.pale_red_middle_12.set_align('center')
        self.pale_red_middle_12.set_align('vcenter')
        self.pale_red_middle_12.set_font_size(12)
        self.pale_red_middle_12.set_text_wrap('True')
        self.pale_red_middle_12.set_bg_color('#F2DCDB')
        self.pale_red_middle_12.set_font_color('black')
        self.pale_red_middle_12.set_border_color('white')

        # Other yellow colors: C49718, F5BD1F, DCAA1B for missing color
        self.neutral_cell = wb.add_format({'border': 2})
        self.neutral_cell.set_align('center')
        self.neutral_cell.set_align('vcenter')
        self.neutral_cell.set_bold()
        self.neutral_cell.set_text_wrap('True')
        self.neutral_cell.set_bg_color('#DCAA1B')
        self.neutral_cell.set_font_color('white')
        self.neutral_cell.set_border_color('white')

        self.neutral_cell_16 = wb.add_format({'border': 2})
        self.neutral_cell_16.set_align('center')
        self.neutral_cell_16.set_align('vcenter')
        self.neutral_cell_16.set_bold()
        self.neutral_cell_16.set_font_size(16)
        self.neutral_cell_16.set_text_wrap('True')
        self.neutral_cell_16.set_bg_color('#DCAA1B')
        self.neutral_cell_16.set_font_color('white')
        self.neutral_cell_16.set_border_color('white')

        self.neutral_cell_12 = wb.add_format({'border': 2})
        self.neutral_cell_12.set_align('center')
        self.neutral_cell_12.set_align('vcenter')
        self.neutral_cell_12.set_bold()
        self.neutral_cell_12.set_font_size(12)
        self.neutral_cell_12.set_text_wrap('True')
        self.neutral_cell_12.set_bg_color('#DCAA1B')
        self.neutral_cell_12.set_font_color('white')
        self.neutral_cell_12.set_border_color('white')

        # Other yellow colors: C49718, F5BD1F, DCAA1B for missing color
        self.left_neutral_cell = wb.add_format({'border': 2})
        self.left_neutral_cell.set_align('vcenter')
        self.left_neutral_cell.set_bold()
        self.left_neutral_cell.set_text_wrap('True')
        self.left_neutral_cell.set_bg_color('#DCAA1B')
        self.left_neutral_cell.set_font_color('white')
        self.left_neutral_cell.set_border_color('white')

        self.missing_cell = wb.add_format({'border': 2})
        self.missing_cell.set_align('center')
        self.missing_cell.set_align('vcenter')
        self.missing_cell.set_bold()
        self.missing_cell.set_text_wrap('True')
        self.missing_cell.set_fg_color('white')
        self.missing_cell.set_bg_color('#1f497d')
        self.missing_cell.set_font_color('#1f497d')
        self.missing_cell.set_border_color('white')
        self.missing_cell.set_pattern(7)

        self.aqua_missing = wb.add_format({'border': 2})
        self.aqua_missing.set_align('center')
        self.aqua_missing.set_align('vcenter')
        self.aqua_missing.set_bold()
        self.aqua_missing.set_text_wrap('True')
        self.aqua_missing.set_fg_color('white')
        self.aqua_missing.set_bg_color('#31869B')
        self.aqua_missing.set_font_color('#31869B')
        self.aqua_missing.set_border_color('white')
        self.aqua_missing.set_pattern(7)

        self.purple_missing = wb.add_format({'border': 2})
        self.purple_missing.set_align('center')
        self.purple_missing.set_align('vcenter')
        self.purple_missing.set_bold()
        self.purple_missing.set_text_wrap('True')
        self.purple_missing.set_fg_color('white')
        self.purple_missing.set_bg_color('#7030A0')
        self.purple_missing.set_font_color('#7030A0')
        self.purple_missing.set_border_color('white')
        self.purple_missing.set_pattern(7)

        self.dark_grey_missing = wb.add_format({'border': 2})
        self.dark_grey_missing.set_align('center')
        self.dark_grey_missing.set_align('vcenter')
        self.dark_grey_missing.set_bold()
        self.dark_grey_missing.set_text_wrap('True')
        self.dark_grey_missing.set_fg_color('white')
        self.dark_grey_missing.set_bg_color('#595959')
        self.dark_grey_missing.set_font_color('#595959')
        self.dark_grey_missing.set_border_color('white')
        self.dark_grey_missing.set_pattern(7)

        self.merge_format = wb.add_format({'align': 'center'})
        self.merge_format.set_align('vcenter')
        self.merge_format.set_bold()
        self.merge_format.set_text_wrap()
        self.merge_format.set_border_color('white')
        self.merge_format.set_border('2')
        self.merge_format.set_font_size('16')
        self.merge_format.set_bg_color('#1f497d')
        self.merge_format.set_font_color('white')

        self.white_back = wb.add_format({'border': 1})
        self.white_back.set_bg_color('white')
        self.white_back.set_align('vcenter')
        self.white_back.set_align('center')
        self.white_back.set_border_color('#1f497d')
        self.white_back.set_bold()
        self.white_back.set_font_color('#1f497d')
        self.white_back.set_font_size('18')

        self.white_small_back = wb.add_format({'border': 1})
        self.white_small_back.set_bg_color('white')
        self.white_small_back.set_align('vcenter')
        self.white_small_back.set_align('center')
        self.white_small_back.set_border_color('#1f497d')
        self.white_small_back.set_bold()
        self.white_small_back.set_font_color('#1f497d')

        self.white_thin_back = wb.add_format({'border': 1})
        self.white_thin_back.set_bg_color('white')
        self.white_thin_back.set_align('vcenter')
        self.white_thin_back.set_align('center')
        self.white_thin_back.set_border_color('#1f497d')
        self.white_thin_back.set_bold()
        self.white_thin_back.set_right()
        self.white_thin_back.set_font_color('#1f497d')

# class RichText:
#     def bios(self, trr_bios, crd_bios):


def replace_unnecesarry(string):
    unnecessary = str(string)
    if ' ' in unnecessary:
        unnecessary = unnecessary.replace(' ', '')
    if 'FW:' in unnecessary:
        unnecessary = unnecessary.replace('FW:', '')
    if ')' in unnecessary:
        unnecessary = unnecessary.replace(')', '')
    if '(' in unnecessary:
        unnecessary = unnecessary.replace('(', '')
    if '#' in unnecessary:
        unnecessary = unnecessary.replace('#', '')
    if '960GB' in unnecessary:
        unnecessary = unnecessary.replace('960GB', '')
    return unnecessary


def requested_configuration(trr_json: dict, key_term_1: str, key_term_2: str, key_term_3: str) -> str:
    """
    Finds configuration within ADO with three key terms based on text segments within the configuration name.
    Returns the requested configuration for potential discrepancies between TRRs and Host configuration.

    :param trr_json: created JSON file for TRR
    :param key_term_1: text segment within configuration name
    :param key_term_2:text segment within configuration name
    :param key_term_3: text segment within configuration name

    :return: requested configuration from ADO
    """
    for dependency in trr_json:
        upper_key_term_1 = str(key_term_1).upper()
        upper_key_term_2 = str(key_term_2).upper()
        upper_key_term_3 = str(key_term_3).upper()
        upper_item = str(dependency).upper()

        if upper_key_term_1 in upper_item \
                and upper_key_term_2 in upper_item \
                and upper_key_term_3 in upper_item:
            configuration = str(trr_json[dependency])
            return configuration


def check_empty_single(trr):
    """
    Check if system configuration or TRR configuration is empty.
    Returns boolean on True/False.

    :param trr: Test Run Request configuration
    :type trr: str
    :return: returns true if correct
    :rtype: bool
    """
    trr = str(trr)
    if trr == "":
        return True
    elif trr.isspace():
        return True
    else:
        return False
